### PR TITLE
Add bsl and mdo icons

### PR DESCRIPTION
**Pull request by nixel2007**
Hi, @Alhadis!
better late than never :)

I want to add new *official* 1C (BSL) icons: bsl.svg for modules (`*.bsl`) and mdo.svg for metadata (like xml but `*.mdo`)
I have no woff2 file in archive, downloaded from Iconmoon.
Also I've deleted old 1C.svg

What else should I do? Is this setup enough for you?

Russians are watching you, lol 👀

### CODE REVIEW

**Comment by Alhadis** [comment]
Добре дан! 👋 Thanks for the PR. I'm afraid there *are* some changes you'll need to make...

1. **We don't delete icons.** Generally what we do is add a new icon, and suffix the old icon with `-old`. For example, when [NSIS](https://github.com/Alhadis/FileIcons/blob/master/charmap.md#NSIS) and [Rollup](https://github.com/Alhadis/FileIcons/blob/master/charmap.md#Rollup) changed their branding, their old icons were kept for posterity reasons.<br><br>This feels different though, since the original icon was never actually official branding. Hell, I don't even know whether it's even a logo. It was my improvisation when I was scouring 1C's site for something to use as an icon. So while I'm happy to replace the old icon (particularly since the new one is clearer), you'll have to update `1C.svg` instead of delete it.

2. **The second icon isn't needed.** Both icons are almost identical; the only difference is `*.mdo`'s icon has a tag-shaped border around it. For stuff like this, we use icon colours to distinguish between two icons of different formats. So you'll ned to kill that one too. =)

3. **The icon isn't scaled to fit its frame.** Don't worry, I've done that for you. Copy+paste this:
```svg
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="512px" height="512px"><path d="M116.3636475,116.3636475v279.2727051H46.5454712V209.4545288H0v-69.8181763h46.5454712v-23.2727051H116.3636475z M344.4363403,232.7272339h72.1454468c-11.6363525-65.1636353-67.4909058-116.3635864-137.309082-116.3635864c-76.7999878,0-139.6363525,62.8363037-139.6363525,139.6363525c0,75.2418213,60.3148193,137.1577148,134.9818115,139.6363525H512v-69.8181763H279.2727051C213,324.3333435,190.9468842,251.4048309,226.2013245,210.1751099c34.8834534-40.5067139,100.8290405-27.6664581,118.4171753,23.0569763"/></svg>
```

IcoMoon seems to have done something weird with the font, so you'll need to revert 2a87003 entirely and start again. :S I'm not sure why it thinks the icons are coloured, and it's created a few blank icon entries. Really looking forward to starting work on a replacement icon generator...

**Comment by nixel2007** [comment]
Thanks for the comments!
1) Sure, I can keep the old one.
2) This one can make trouble. Is the deleting of mdo a tough position?
These icons was provided by 1C designers directly, I'll need another round of negotiation to apply it. Could you make an exception this time?
3) Thanks a lot :) Maybe I'll ask you to scale the mdo icon too, if you decide to leave it.

Reverting and start again: no problem at all, i'll do it.

**Comment by Alhadis** [comment]
Hrm, alright, forget it then. We'll include both, but please rename the MDO icon `1C-Alt.svg`, if you wouldn't mind. =)

I've also scaled and cleaned it up for you:
```svg
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="512px" height="512px"><path d="M433.8036194,79.1272736H87.5054474L0,256l87.5054474,176.8727417h346.2981567C476.6254272,432.8727417,512,397.4981995,512,354.6763611V157.3236389C512,114.5018234,478.4872742,79.1272736,433.8036194,79.1272736z M433.8038025,118.2254639c22.3418274,0,39.0982056,16.7563477,39.0982056,39.0981903v197.3527069c-0.0001831,22.3418274-16.7565613,39.098175-39.0983887,39.098175H117.294548c0,0-78.1963577-126.6036682-78.1963577-134.0509033l78.1963577-141.4981689H433.8038025z M350.0217896,235.5200043c-13.6784058-32.9733124-57.6777649-38.0210419-79.6305542-9.5905304c-23.1878662,31.6891479-1.7380981,74.2789612,36.8087769,74.7541504h119.1563416v37.2363586H307.2000122C221.5,334.25,200,238.75,250.210083,192.7695923c47.2904053-43.7007446,124.6932983-19.8923035,138.999939,42.750412C389.210022,235.5200043,350.0220032,235.5200043,350.0217896,235.5200043z M204.7999878,172.2181396v167.5636597h-37.2363281V237.3817749h-37.2363892v-37.2363281h37.2363892v-27.9273071H204.7999878z"/></svg>
```

**Comment by nixel2007** [comment]
@Alhadis thank you!
to make it clear - I need to add to icomoon both new and old icon (1C-old.svg) and regenerate fonts.
 is it correct?

**Comment by nixel2007** [comment]
Or just add a new one?

**Comment by Alhadis** [comment]
Eh, it might be easier to ditch it and reimport. Here're the steps:

Step-1Step-2

Then when you're on the **Projects** page:

Step-3 Step-4

**Comment by nixel2007** [comment]
I mean, should I do anything with your version of 1c icon other than rename it to 1C-old.
Okey, i'll just reimport all stuff.

**Comment by Alhadis** [comment]
No, don't rename it. Just replace its contents with the SVG source of the first icon I gave you. :)

So in the end, we should have:

- **1C.svg** (updated)
- **1C-Alt.svg** (the icon for `.mdo` files)

**Comment by nixel2007** [comment]
okey, i've got it. sorry for my confusion :)

2016-12-23 20:39 GMT+03:00 John Gardner <notifications@github.com>:

**Comment by Alhadis** [comment]
Don't apologise. :) I know this process is a bit fiddly, which is why I look forward to developing a more streamlined process so everything is completely automated.

**Comment by Alhadis** [comment]
Hope you don't mind, but I've gone and updated the icons for you. =)

You'll see this in the next release.

**Comment by nixel2007** [comment]
Thanks a lot! :+1:

**Pull request closed without merging**
