### PR TITLE
Fix icon for pug

### PR DESCRIPTION
**Pull request by blade254353074**
image

Convert bear to the pug, 😂 😂 😂

### CODE REVIEW

**Comment by blade254353074** [comment]
[pugjs/pug](https://github.com/pugjs/pug)

**Comment by Alhadis** [comment]
There's a little too much detail:

BeforeAfter

[Could you use this](http://pastebin.com/ZXtVz6aT) instead? I've reduced some of the detail so the edges look sharper at icon-size:



Also, it's possible some people might like the older icon better (since it *is* quite different)... could you add this as a new icon, please? :) We'll make it the new default, but it's nice to give people the option to pick.

**Comment by blade254353074** [comment]
Your [optimized pug version](http://pastebin.com/ZXtVz6aT) looks better.
My friends said the old pug icon looks like a crab...
I don't know how to name this icon as a new one, pug is suitable.

**Comment by Alhadis** [comment]
Just name it `pug`, mate. :) Rename the old one `pug-alt`. You can leave the tags as they are, they don't have to be unique.

**Comment by blade254353074** [comment]
OK, Let me do this. I will add a new pull request.

**Comment by Alhadis** [comment]
Alright mate, you can close this when you're ready. :)

**Pull request closed without merging**
