### PR TITLE
Add new pug icon & rename pug.svg to pug-alt.svg

### PR DESCRIPTION
**Pull request by blade254353074**
After #2 

image

### CODE REVIEW

**Comment by Alhadis** [comment]
Thank you! =)

**Comment by blade254353074** [comment]
> new Date()  
< Sat Sep 17 2016 01:05:53 GMT+0800 (CST)

What time is it now, in your place?

**Comment by Alhadis** [comment]
In Australia?

Too. Damn. Late.

Or early, depending on how you look at it:

screen shot 2016-09-17 at 3 10 02 am

I regret absolutely nothing.

**Comment by blade254353074** [comment]
I'm in Beijing, China, two hours earlier than you.
I thought you were in the United States... 😂

Your github profile bio is very interesting.

It's time to go to sleep...Good night~

**Comment by Alhadis** [comment]
Hah, no. :-) I'm from Melbourne.

晚安！

**Pull request merged**
